### ISSUE TITLE
only module 3 included  in aggregated html report 

### ISSUE THREAD

**Issue by samarthgupta437** [scoverage/scoverage-maven-samples#1]
on running `mvn site` from "aggregation" dir , the aggregated report generated in target contains only package 3 in index.html and in overview.html. 
attaching the screen shot 
<img width="718" alt="screen shot 2016-01-06 at 1 30 34 pm" src="https://cloud.githubusercontent.com/assets/1697625/12137858/225298f0-b47a-11e5-8050-dc55fae6ba5c.png">

**Comment by gslowikowski** [comment]
This is strange. It works properly for me. Every module contains non-aggregated report and aggregated report in `aggregation/target` directory contains all three classes.

Execute `mvn clean site -X` and attach execution log, please.

**Comment by samarthgupta437** [comment]
worked for me as well. Seems like i was missing the `clean` keyword before `site`  . Apologies for false alarm. 
 Thanks
