### ISSUE TITLE
Won't this run tests twice?

### ISSUE THREAD

**Issue by babineaum** [scoverage/scoverage-maven-samples#2]
https://github.com/scoverage/scoverage-maven-samples/blob/afc03ac889dd90ff34360f7bf1cca76da4f8aec9/different-test-frameworks/scalatest/pom.xml#L160

Accoring to this closed issue https://github.com/scoverage/scoverage-maven-plugin/issues/39, this pom file would run tests twice, is that correct?

**Comment by babineaum** [comment]
@gslowikowski wondering if you might be able to help me out. i tried to follow what you were saying over in the closed ticket i reffed above but im still getting 2 runs of test if i turn of all scoverage i dont get a report... so im kinda confused as to why you said to disable all tasks for scoverage in the pom.xml

**Comment by gslowikowski** [comment]
Hi @babineaum 

Sorry for not responding for some time.

IMPORTANT!
When I'm writing about (not) adding scoverage tasks to `pom.xml` file I'm thinking about `build` section, not `reporting`.  In short, `reporting` is OK.

Generally, I never add scoverage tasks to my poms (`build` section).
If I want coverage check, I run something like this `mvn clean package scoverage:check`.
If I want coverage report - `mvn scoverage:report`
If report must be added to Maven site, it has to be added to reporting section, like in the line you cited above.
If you run e.g. `mvn test scoverage:check` or `mvn test scoverage:report` the tests will run twice, once on uninstrumented classes (in `test` task) and second time on instrumented classes (in `test` task executed in lifecycle forked by `scoverage:report` task)

The issue https://github.com/scoverage/scoverage-maven-plugin/issues/39 was about forking scoverage lifecycle from already forked scoverage lifecycle. It is possible, but does not make sense.

**Comment by babineaum** [comment]
Hmmm ok well i seem to have the same problem as the other person "ghost". 

I guess my question is, is there a way to run a 'mvn clean install' and have the build create an artifact that I can deploy and also run instrumented tests without running the non instrumented tests as well? 

Edit: I'll note that I am getting two runs of the tests, one pre the scoverage fork during the test phase, by scalattest-maven-plugin and the other during the scoverage fork when scoverage calls scalatest-maven-plugin and runs tests after instrumentation.

**Comment by gslowikowski** [comment]
You need two Maven calls, for example:
- `mvn clean install -DskipTests`
- `mvn scoverage:report`

There is no way (IMO) to set and clear `skipTests` flag interpreted by Surefire plugin depending on the context (scoverage or not).

**Comment by tenstriker** [comment]
For me single `mvn clean process-classes scoverage:report` command works. proccess-classes generates classed dir under target so I can run my application. I don't attach any scoverage goal to build lifecycle in pom configuration.

**Comment by ahmedriza** [comment]
@gslowikowski 
``mvn clean package scoverage:check``
still runs the build and tests twice. Is there a way to run the build and tests just once (similar to what JaCoCo does for Java) ?

**Comment by gslowikowski** [comment]
There is a way to avoid running tests twice now. Check this issue scoverage/scoverage-maven-plugin#61 please.

**Comment by gliu-nova** [comment]
solution:
remove scoverage:report goal, then run
mvn scoverage:report AFTER your mvn clean test/verify
